"""add capacity and spots taken

Revision ID: 3bfe85e044aa
Revises: 33c1608d71aa
Create Date: 2015-04-05 21:23:38.896852

"""

# revision identifiers, used by Alembic.
revision = '3bfe85e044aa'
down_revision = '33c1608d71aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoot_location_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'locations', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column(u'locations', sa.Column('spots_taken', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'locations', 'spots_taken')
    op.drop_column(u'locations', 'capacity')
    op.drop_table('scoot_location_events')
    ### end Alembic commands ###
